apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: 309276322609.dkr.ecr.ap-southeast-1.amazonaws.com/frontend
    newTag: '26'

commonAnnotations:
  image-updater.argoproj.io/interval: "1m"  # Check for updates every 1 minutes
  image-updater.argoproj.io/enabled: "true"  # Enable ArgoCD Image Updater
  argocd-image-updater.argoproj.io/image-list: 309276322609.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:*
  argocd-image-updater.argoproj.io/write-back-method: git       
  argocd-image-updater.argoproj.io/git-branch: master      
  argocd-image-updater.argoproj.io/write-back-target: kustomization
  argocd-image-updater.argoproj.io/myalias.force-update: "true"

resources:
  - deployment.yaml
  - service.yaml